csa-lab-3-moratorium:
  stage: test
  image:
    name: ryukzak/python-tools
    entrypoint: [""]
  script:
    - poetry install
    -  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    -  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - coverage run -m pytest --update-goldens
    - find . -type f -name "*.py" | xargs -t coverage report
    - ruff format --check .

